souffle: souffle::ast::analysis::FunctorAnalysis Class Reference
souffle::ast::analysis::FunctorAnalysis Class Reference
#include <Functor.h>
Public Member Functions
FunctorAnalysis ()
TypeAttribute getArgType (const Functor *functor, const size_t idx) const
Return argument type of functor.
const std::vector< TypeAttribute > & getArgTypes (const UserDefinedFunctor &udf) const
TypeAttribute getReturnType (const Functor *functor) const
Return return type of functor.
bool isStateful (const UserDefinedFunctor *udf) const
Return whether a UDF is stateful.
void print (std::ostream &) const override
print the analysis result in HTML format
void run (const TranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::ast::analysis::Analysis
Analysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~Analysis ()=default
Static Public Member Functions
static bool isMultiResult (const Functor &functor)
Static Public Attributes
static constexpr const char * name = "functor-analysis"
Private Attributes
std::map< std::string, const IntrinsicFunctorInfo * > functorInfo
std::map< std::string, const FunctorDeclaration * > udfDeclaration
Additional Inherited Members
Protected Attributes inherited from souffle::ast::analysis::Analysis
const std::string identifier
Detailed Description
Definition at line 37 of file Functor.h.
Constructor & Destructor Documentation
FunctorAnalysis()
souffle::ast::analysis::FunctorAnalysis::FunctorAnalysis () inline
Definition at line 47 of file Functor.h.
Member Function Documentation
getArgType()
TypeAttribute souffle::ast::analysis::FunctorAnalysis::getArgType (const Functor * functor, const size_t idx) const
Return argument type of functor.
Definition at line 71 of file Functor.cpp.
            {
         fatal("Missing functor type.");
     }
 }
 bool FunctorAnalysis::isMultiResult(const Functor& functor) {
     if (isA<UserDefinedFunctor>(functor)) {
         return false;
     } else if (auto* intrinsic = as<IntrinsicFunctor>(functor)) {
         auto op = intrinsic->getFunctionOp();
getArgTypes()
const std::vector< TypeAttribute > & souffle::ast::analysis::FunctorAnalysis::getArgTypes (const UserDefinedFunctor & udf) const
Definition at line 66 of file Functor.cpp.
{
         return udfDeclaration.at(udf->getName())->getArgsTypes().at(idx);
     } else if (auto* intrinsic = as<IntrinsicFunctor>(functor)) {
References souffle::ast::UserDefinedFunctor::getName(), and udfDeclaration.
getReturnType()
TypeAttribute souffle::ast::analysis::FunctorAnalysis::getReturnType (const Functor * functor) const
Return return type of functor.
Definition at line 56 of file Functor.cpp.
{
     return udfDeclaration.at(udf.getName())->getArgsTypes();
 }
 /** Return argument type of functor */
isMultiResult()
bool souffle::ast::analysis::FunctorAnalysis::isMultiResult (const Functor & functor) static
Definition at line 82 of file Functor.cpp.
            {
         fatal("Missing functor type.");
     }
 }
 }  // namespace souffle::ast::analysis
isStateful()
bool souffle::ast::analysis::FunctorAnalysis::isStateful (const UserDefinedFunctor * udf) const
Return whether a UDF is stateful.
Definition at line 52 of file Functor.cpp.
{
         return udfDeclaration.at(udf->getName())->getReturnType();
print()
void souffle::ast::analysis::FunctorAnalysis::print (std::ostream &) const inline override virtual
print the analysis result in HTML format
Reimplemented from souffle::ast::analysis::Analysis.
Definition at line 51 of file Functor.h.
 :
     std::map<std::string, const FunctorDeclaration*> udfDeclaration;
run()
void souffle::ast::analysis::FunctorAnalysis::run (const TranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::ast::analysis::Analysis.
Definition at line 32 of file Functor.cpp.
{
         // any valid candidate will do. pick the first.
         try {
             auto candidates = validOverloads(typeAnalysis, functor);
             if (!candidates.empty()) {
                 functorInfo[functor.getFunction()] = &candidates.front().get();
             }
         } catch (...) {
             // type analysis in validOverloads failed.
         }
     });
 }
 bool FunctorAnalysis::isStateful(const UserDefinedFunctor* udf) const {
     return udfDeclaration.at(udf->getName())->isStateful();
 }
 TypeAttribute FunctorAnalysis::getReturnType(const Functor* functor) const {
References functorInfo, souffle::ast::IntrinsicFunctor::getFunction(), and souffle::ast::validOverloads().
Field Documentation
functorInfo
std::map<std::string, const IntrinsicFunctorInfo*> souffle::ast::analysis::FunctorAnalysis::functorInfo private
Definition at line 68 of file Functor.h.
Referenced by run().
name
constexpr const char* souffle::ast::analysis::FunctorAnalysis::name = "functor-analysis" static constexpr
Definition at line 45 of file Functor.h.
udfDeclaration
std::map<std::string, const FunctorDeclaration*> souffle::ast::analysis::FunctorAnalysis::udfDeclaration private
Definition at line 67 of file Functor.h.
Referenced by getArgTypes().
The documentation for this class was generated from the following files:
ast/analysis/Functor.h
ast/analysis/Functor.cpp